sudo: required
language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "2.7"
  - "3.4"
  - "3.5"
services:
  - docker
before_install:
  - sudo docker pull pynedist/pyne-ubuntu
install:
   - sudo docker run pynedist/pyne-ubuntu /bin/sh -c "git clone https://github.com/pyne/pyne"
   - sudo docker commit `sudo docker ps -l | tail -n1 | awk '{print $1}'` pynedist/pyne-ubuntu
   - sudo docker run pynedist/pyne-ubuntu /bin/sh -c "cd pyne"
   - sudo docker commit `sudo docker ps -l | tail -n1 | awk '{print $1}'` pynedist/pyne-ubuntu
   - sudo docker run pynedist/pyne-ubuntu /bin/sh -c "python setup.py install --user -- -DMOAB_LIBRARY=/root/opt/moab/lib/libMOAB.so -DMOAB_INCLUDE_DIR=/root/opt/moab/include"
   - sudo docker commit `sudo docker ps -l | tail -n1 | awk '{print $1}'` pynedist/pyne-ubuntu
script:
   - sudo docker run pynedist/pyne-ubuntu /bin/bash -c "/root/.local/bin/nuc_data_make" 
   - sudo docker commit `sudo docker ps -l | tail -n1 | awk '{print $1}'` pynedist/pyne-ubuntu
   - sudo docker run pynedist/pyne-ubuntu /bin/bash -c "cd tests"
   - sudo docker commit `sudo docker ps -l | tail -n1 | awk '{print $1}'` pynedist/pyne-ubuntu
   - sudo docker run pynedist/pyne-ubuntu /bin/bash -c "./travis-run-tests.sh"
   - sudo docker commit `sudo docker ps -l | tail -n1 | awk '{print $1}'` pynedist/pyne-ubuntu
  # Build the pyne-amalgamation test program 
  # - git clone https://github.com/pyne/pyne-amalgamation.git
  #- cd ..
  #- python amalgamate.py
  #- mv pyne.h pyne.cpp tests/pyne-amalgamation
  #- cd tests
  #- BASE=/home/travis/miniconda make -C pyne-amalgamation


